apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: library-gateway
  namespace: istio-system
spec:
  gatewayClassName: istio
  listeners:
  - name: http
    hostname: "*.apps.sno-oci.re9r.work.gd"
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: book-route
  namespace: library-project
spec:
  parentRefs:
  - name: library-gateway
    namespace: istio-system
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /api/book
    backendRefs:
    - name: book-service
      port: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: inventory-route
  namespace: library-project
spec:
  parentRefs:
  - name: library-gateway
    namespace: istio-system
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /api/inventory
    backendRefs:
    - name: inventory-service
      port: 8081
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: order-route
  namespace: library-project
spec:
  parentRefs:
  - name: library-gateway
    namespace: istio-system
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /api/order
    backendRefs:
    - name: order-service
      port: 8082
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: email-route
  namespace: library-project
spec:
  parentRefs:
  - name: library-gateway
    namespace: istio-system
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /api/email
    backendRefs:
    - name: email-service
      port: 8083
