spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

spring.data.mongodb.database=LibraryDB
logging.level.org.springframework.data.mongodb.core.MongoTemplate=debug
spring.data.mongodb.auto-index-creation=true

server.port=0
spring.application.name=book-service


spring.cache.cache-names=books, authors, genres, publishers
spring.cache.caffeine.spec=maximumSize=500, expireAfterAccess=60m